# This workflow will build a Java project with Maven and cache/restore dependencies
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# Note: This workflow uses third-party actions governed by separate terms of service.

name: Java CI with Maven

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 22 with Maven cache
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
        
      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      # Step 4: Run tests with Maven
      - name: Run tests with Maven
        run: mvn test
        
      # Optional: Update dependency graph for Dependabot
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
